add hami release process

diff --git a/.github/workflows/auto-release.yaml b/.github/workflows/auto-release.yaml
--- a/.github/workflows/auto-release.yaml
+++ b/.github/workflows/auto-release.yaml
@@ -22,11 +22,47 @@ on:
 permissions: write-all
 
 jobs:
-  get-tag:
+  pre-release:
     runs-on: ubuntu-latest
+    permissions:
+      contents: write
     outputs:
       tag: ${{ env.RUN_TAG }}
     steps:
+    - name: Check Version
+      run: |
+        TagVersion="${{ env.RUN_TAG }}"
+        RecordVersion=` cat VERSION  | tr -d ' ' | tr -d '\n' `
+        if [ "$RecordVersion" != "$TagVersion" ] ; then
+          echo "error, version $RecordVersion of '/VERSION' is different with Tag $TagVersion "
+          exit 1
+        fi
+        #no need to check chart version, which will auto update to /VERSION by CI
+      # generate release notes for the new release branch
+    - name: Generate pre release notes
+      if: startsWith(github.ref, 'refs/tags/')
+      uses: softprops/action-gh-release@v2
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        prerelease: true
+        generate_release_notes: true
+
+  ensure-tag:
+    runs-on: ubuntu-latest
+    needs: pre-release
+    outputs:
+      tag: ${{ env.RUN_TAG }}
+    steps:
+      - name: Free disk space
+        # https://github.com/actions/virtual-environments/issues/709
+        run: |
+          echo "=========original CI disk space"
+          df -h
+          sudo rm -rf "/usr/local/share/boost"
+          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
+          echo "=========after clean up, the left CI disk space"
+          df -h
       - name: Get Ref
         id: get_ref
         run: |
@@ -53,15 +89,6 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: ${{ env.RUN_TAG }}
-      - name: Check Version
-        run: |
-          TagVersion="${{ env.RUN_TAG }}"
-          RecordVersion=` cat VERSION  | tr -d ' ' | tr -d '\n' `
-          if [ "$RecordVersion" != "$TagVersion" ] ; then
-            echo "error, version $RecordVersion of '/VERSION' is different with Tag $TagVersion "
-            exit 1
-          fi
-          #no need to check chart version, which will auto update to /VERSION by CI
         # if branch exists, the action will no fail, and it output created=false
       - name: release Y branch
         uses: peterjgrainger/action-create-branch@v3.0.0
@@ -70,47 +97,46 @@ jobs:
         with:
           branch: 'release-${{ env.RUN_YBranchName }}'
           sha: '${{ github.sha }}'
-        # generate release notes for the new release branch
-      - name: Generate release notes
-        if: startsWith(github.ref, 'refs/tags/')
-        uses: softprops/action-gh-release@v2
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          prerelease: true
-          generate_release_notes: true
+
+
   release-image:
-    needs: get-tag
+    needs: ensure-tag
     uses: ./.github/workflows/call-release-image.yaml
     with:
-      ref: ${{ needs.get-tag.outputs.tag }}
+      ref: ${{ needs.ensure-tag.outputs.tag }}
     secrets: inherit
 
   release-chart:
-    needs: [get-tag]
-    # needs: [build-release-image, get-tag]
+    needs: [ensure-tag]
     uses: ./.github/workflows/call-release-helm.yaml
     with:
-      ref: ${{ needs.get-tag.outputs.tag }}
+      ref: ${{ needs.ensure-tag.outputs.tag }}
       submit: true
     secrets: inherit
+
+  # generate changelog and update to github releases pages
+  release-notes:
+    needs: [release-chart,release-image]
+    uses: ./.github/workflows/call-release-notes.yaml
+    with:
+      ref: ${{ needs.ensure-tag.outputs.tag }}
   
   release-website:
-    needs: [release-chart,release-image]
+    needs: [release-notes]
     uses: ./.github/workflows/call-release-website.yaml
     with:
-      ref: ${{ needs.get-tag.outputs.tag }}
+      ref: ${{ needs.ensure-tag.outputs.tag }}
   # excute a full e2e test when hami release
   release-e2e:
-    needs: [release-chart,release-image]
+    needs: [release-notes]
     uses: ./.github/workflows/call-e2e.yaml
     with:
-      ref: ${{ needs.get-tag.outputs.tag }}
+      ref: ${{ needs.ensure-tag.outputs.tag }}
 
   # excute a compatibility test when hami release
   release-e2e-upgrade:
-      needs: [release-chart,release-image]
+      needs: [release-notes]
       uses: ./.github/workflows/call-e2e-upgrade.yaml
       with:
-        ref: ${{ needs.get-tag.outputs.tag }}
+        ref: ${{ needs.ensure-tag.outputs.tag }}
   
